### ISSUE TITLE
Photos not showing up in chat

### ISSUE THREAD

**Issue by klydeinside** [PeteDevoy/irc-style-for-messenger-com#2]
The photos that people send me are now blank. They show complete white. I can view them fine on the Facebook website and also without the script. Can you please check this or tell me how to fix it myself? I know some coding and could figure it out if I knew what to check for possibly. I just want it fixed because I love this script. As shown in the screenshot, you can see the picture link with the arrow and all that white space is supposed to be a picture. 
![screenshot_46](https://user-images.githubusercontent.com/37005235/53997279-374bd480-4101-11e9-8eea-445087fa8dbb.png)

**Comment by PeteDevoy** [comment]
@xklydex Thanks for the feedback. I will have a look.  Hacking at the page style isn't too hard if you do want to try...

When you're on the page press the `F12` key to open your browser's developer tools then use select element tool to click the element (an "image" in this case) on the page:

![image](https://user-images.githubusercontent.com/4375326/54089052-8e99b100-435c-11e9-88e9-d109da5f88d3.png)

And then look in the `class="..."` tag of the element and also styles pane and have a fiddle to try and work out what style rule(s) is controlling the style of that element:

![image](https://user-images.githubusercontent.com/4375326/54089068-cbfe3e80-435c-11e9-8a3a-8673ef223bec.png)

Then after finding a style rule that appropriately targets the elements you are trying to change you can modify it as desired and copy and paste that into the user-defined stylesheet.

**Comment by klydeinside** [comment]
> @xklydex Thanks for the feedback. I will have a look. Hacking at the page style isn't too hard if you do want to try...
> 
> When you're on the page press the `F12` key to open your browser's developer tools then use select element tool to click the element (an "image" in this case) on the page:
> 
> ![image](https://user-images.githubusercontent.com/4375326/54089052-8e99b100-435c-11e9-88e9-d109da5f88d3.png)
> 
> And then look in the `class="..."` tag of the element and also styles pane and have a fiddle to try and work out what style rule(s) is controlling the style of that element:
> 
> ![image](https://user-images.githubusercontent.com/4375326/54089068-cbfe3e80-435c-11e9-8a3a-8673ef223bec.png)
> 
> Then after finding a style rule that appropriately targets the elements you are trying to change you can modify it as desired and copy and paste that into the user-defined stylesheet.

Thanks. I know a little about that kind of stuff. There's not much else I don't like in the script to be honest. Been using it forever and love it. Just sucks the other day all my pics started going white.

**Comment by PeteDevoy** [comment]
@xklydex Glad you've got good use out of it!  I'm about to upload the fix so if you check back in 10 minutes you should have it.
