### ISSUE TITLE
New Facebook update? Lots of things broken. 

### ISSUE THREAD

**Issue by klydeinside** [PeteDevoy/irc-style-for-messenger-com#3]
Hi there. Coming back to let you know I just opened this today and there is so much wrong. Maybe Facebook updated their code? I tried it on 3 different browsers and am getting the same results.

 
![Screenshot_28](https://user-images.githubusercontent.com/37005235/56693423-07a15d80-66aa-11e9-99a7-d72d19715df1.png)

**Comment by PeteDevoy** [comment]
Thanks, I do not have time to fix right now but will try on the weekend

**Comment by klydeinside** [comment]
> Thanks, I do not have time to fix right now but will try on the weekend

Hey, no worries! Just wanted to toss it out there.

**Comment by PeteDevoy** [comment]
![irc-style-messenger](https://user-images.githubusercontent.com/4375326/62427090-7482b580-b6e5-11e9-8433-0ce0f3b298a1.png)
I think this largely fixed itself, at least for me.  I did finally fix the chat bubble thing and the updated style is on userstyles.org.  If it's not fixed for you feel free to lmk what browser you are using and I'll reopen the issue.
